import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

const dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig(({ command }) => ({
  plugins: [
    react(),
    VitePWA({
      // Silent background update: no "new version available" interruption
      // mid-flow (RNF-01 of the SRS — critical flows must stay reachable in
      // "up to 3 taps" during live on-site use; a reload prompt would break that).
      registerType: 'autoUpdate',
      manifest: {
        name: 'Mason Connect',
        short_name: 'Mason Connect',
        theme_color: '#855023',
        background_color: '#F7F1E4',
        display: 'standalone',
        start_url: '/painel',
        icons: [
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'pwa-maskable-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
        // No `orientation` lock — desktop stays fully usable.
      },
      // Default `generateSW` strategy. `globPatterns` is set explicitly
      // (its own default only covers Vite's tracked build graph — JS/CSS
      // entry chunks, index.html, and the manifest icons) to also sweep in
      // apple-touch-icon.png and the @fontsource woff/woff2 files, which
      // otherwise never make it into the precache list even though they ship
      // in dist/. No `workbox.runtimeCaching` — there are no network/API
      // calls to cache yet; screens ship with mock data embedded in the bundle.
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2}'],
      },
    }),
  ],
  resolve: {
    alias:
      command === 'serve'
        ? [
            {
              // Dev only: resolve the design-system straight from its source for
              // instant HMR, without needing `tsup --watch` running alongside this
              // dev server. `vite build` never takes this branch — production
              // resolves the published package (dist/index.js) normally.
              //
              // Anchored regex, not a plain string key: Vite/rollup's alias
              // matcher treats a string `find` as a *prefix* match
              // (`importee.startsWith(find + '/')`), which would also catch
              // `mason-connect-design-system/dist/styles.css` and wrongly
              // redirect it at this same .ts file. The CSS side must stay
              // unaliased — main.tsx always imports the real `dist/styles.css`,
              // generated by scanning `design-system/src/**` and therefore
              // already covering every class the components use.
              find: /^mason-connect-design-system$/,
              replacement: path.resolve(dirname, '../design-system/src/index.ts'),
            },
          ]
        : [],
  },
  server: {
    fs: {
      // Permit serving design-system/src, which lives outside this workspace
      // root — required for the dev-mode alias above to work.
      allow: ['..'],
    },
  },
}));
